"""snarkjs compatibility layer — parse/export vkey.json, proof.json, public.json.

Supports verification of proofs generated by circom + snarkjs using py-ethclient.

Usage:
    import json
    from ethclient.zk.snarkjs_compat import verify_snarkjs

    vk = json.load(open("verification_key.json"))
    proof = json.load(open("proof.json"))
    public = json.load(open("public.json"))
    assert verify_snarkjs(vk, proof, public)
"""

from __future__ import annotations

from ethclient.zk import groth16
from ethclient.zk.types import G1Point, G2Point, Proof, VerificationKey


def _parse_g1(arr: list[str]) -> G1Point:
    """Parse snarkjs G1 point: ["x", "y", "1"] (projective, but always affine)."""
    x = int(arr[0])
    y = int(arr[1])
    # snarkjs uses "1" for z-coordinate in affine representation
    return G1Point(x, y)


def _parse_g2(arr: list[list[str]]) -> G2Point:
    """Parse snarkjs G2 point: [["x_imag","x_real"], ["y_imag","y_real"], ["1","0"]].

    NOTE: snarkjs uses [c1, c0] ordering (imaginary first) for FQ2 coefficients.
    """
    x_imag = int(arr[0][0])
    x_real = int(arr[0][1])
    y_imag = int(arr[1][0])
    y_real = int(arr[1][1])
    return G2Point(x_real, x_imag, y_real, y_imag)


def _export_g1(point: G1Point) -> list[str]:
    """Export G1 point to snarkjs format."""
    return [str(point.x), str(point.y), "1"]


def _export_g2(point: G2Point) -> list[list[str]]:
    """Export G2 point to snarkjs format."""
    return [
        [str(point.x_imag), str(point.x_real)],
        [str(point.y_imag), str(point.y_real)],
        ["1", "0"],
    ]


def parse_snarkjs_vkey(data: dict) -> VerificationKey:
    """Parse a snarkjs verification_key.json into VerificationKey."""
    alpha = _parse_g1(data["vk_alpha_1"])
    beta = _parse_g2(data["vk_beta_2"])
    gamma = _parse_g2(data["vk_gamma_2"])
    delta = _parse_g2(data["vk_delta_2"])

    ic = [_parse_g1(p) for p in data["IC"]]

    return VerificationKey(
        alpha=alpha,
        beta=beta,
        gamma=gamma,
        delta=delta,
        ic=ic,
    )


def parse_snarkjs_proof(data: dict) -> Proof:
    """Parse a snarkjs proof.json into Proof."""
    a = _parse_g1(data["pi_a"])
    b = _parse_g2(data["pi_b"])
    c = _parse_g1(data["pi_c"])
    return Proof(a=a, b=b, c=c)


def parse_snarkjs_public(data: list[str]) -> list[int]:
    """Parse a snarkjs public.json into list of integers."""
    return [int(x) for x in data]


def export_snarkjs_vkey(vk: VerificationKey) -> dict:
    """Export VerificationKey to snarkjs verification_key.json format."""
    return {
        "protocol": "groth16",
        "curve": "bn128",
        "nPublic": vk.num_public_inputs,
        "vk_alpha_1": _export_g1(vk.alpha),
        "vk_beta_2": _export_g2(vk.beta),
        "vk_gamma_2": _export_g2(vk.gamma),
        "vk_delta_2": _export_g2(vk.delta),
        "IC": [_export_g1(p) for p in vk.ic],
    }


def export_snarkjs_proof(proof: Proof) -> dict:
    """Export Proof to snarkjs proof.json format."""
    return {
        "pi_a": _export_g1(proof.a),
        "pi_b": _export_g2(proof.b),
        "pi_c": _export_g1(proof.c),
        "protocol": "groth16",
        "curve": "bn128",
    }


def verify_snarkjs(
    vkey_json: dict,
    proof_json: dict,
    public_json: list[str],
) -> bool:
    """One-step verification of snarkjs proof/vkey/public.

    Args:
        vkey_json: Contents of verification_key.json
        proof_json: Contents of proof.json
        public_json: Contents of public.json (list of decimal strings)

    Returns:
        True if the proof is valid.
    """
    vk = parse_snarkjs_vkey(vkey_json)
    proof = parse_snarkjs_proof(proof_json)
    public_inputs = parse_snarkjs_public(public_json)
    return groth16.verify(vk, proof, public_inputs)
