"""NativeProverBackend — subprocess-based Groth16 proving via rapidsnark/snarkjs.

Delegates proof generation to external binaries while keeping witness computation
and verification in Python. Circuit construction and witness logic are reused
from Groth16ProofBackend.
"""

from __future__ import annotations

import json
import logging
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from ethclient.l2.interfaces import ProofBackend, StateTransitionFunction
from ethclient.l2.prover import _to_field
from ethclient.l2.types import L2Tx
from ethclient.zk.circuit import Circuit, _field, FIELD_MODULUS
from ethclient.zk import groth16
from ethclient.zk.r1cs_export import export_r1cs_binary, export_witness_json
from ethclient.zk.snarkjs_compat import (
    parse_snarkjs_proof,
    parse_snarkjs_vkey,
)
from ethclient.zk.types import Proof, ProvingKey, VerificationKey

logger = logging.getLogger(__name__)


class NativeProverBackend(ProofBackend):
    """Proof backend that delegates proving to native binaries.

    Witness computation stays in Python (fast enough).
    Proof generation is delegated to rapidsnark or snarkjs CLI.
    Verification uses Python (fast, no native binary needed).

    Working directory layout:
        circuit.r1cs    — R1CS binary
        circuit.zkey    — Proving key (generated by snarkjs)
        vkey.json       — Verification key
        witness.json    — Current witness (overwritten per proof)
        proof.json      — Latest proof output
        public.json     — Latest public inputs
    """

    def __init__(
        self,
        prover_binary: str = "rapidsnark",
        setup_binary: str = "snarkjs",
        working_dir: Optional[str] = None,
        fallback_verify: bool = True,
        prove_timeout: int = 300,
    ) -> None:
        self._prover_binary = prover_binary
        self._setup_binary = setup_binary
        self._working_dir = Path(working_dir) if working_dir else None
        self._fallback_verify = fallback_verify
        self._prove_timeout = prove_timeout

        self._pk: Optional[ProvingKey] = None
        self._vk: Optional[VerificationKey] = None
        self._circuit: Optional[Circuit] = None
        self._max_txs: int = 0
        self._is_setup = False
        self._zkey_path: Optional[Path] = None

    def setup(self, stf: StateTransitionFunction, max_txs_per_batch: int) -> None:
        """Build circuit, export R1CS, run native trusted setup."""
        self._max_txs = max_txs_per_batch
        self._circuit = self._build_circuit(max_txs_per_batch)

        # Ensure working directory
        if self._working_dir is None:
            self._working_dir = Path(tempfile.mkdtemp(prefix="l2_prover_"))
        self._working_dir.mkdir(parents=True, exist_ok=True)

        # Export R1CS binary
        r1cs_path = self._working_dir / "circuit.r1cs"
        r1cs_data = export_r1cs_binary(self._circuit)
        r1cs_path.write_bytes(r1cs_data)

        # Run native trusted setup (snarkjs groth16 setup)
        zkey_path = self._working_dir / "circuit.zkey"
        vkey_path = self._working_dir / "vkey.json"

        try:
            self._run_setup(r1cs_path, zkey_path, vkey_path)
            self._zkey_path = zkey_path

            # Load verification key from snarkjs output
            vkey_data = json.loads(vkey_path.read_text())
            self._vk = parse_snarkjs_vkey(vkey_data)
        except (OSError, subprocess.SubprocessError) as e:
            # Fallback to Python setup if native binary not available
            logger.warning("Native setup failed (%s), falling back to Python setup", e)
            self._pk, self._vk = groth16.setup(self._circuit)

        self._is_setup = True
        logger.info("NativeProver setup complete: max_txs=%d", max_txs_per_batch)

    def prove(
        self,
        old_state_root: bytes,
        new_state_root: bytes,
        transactions: list[L2Tx],
        tx_commitment: bytes,
    ) -> Proof:
        """Generate proof via native binary, or fallback to Python."""
        if not self._is_setup:
            raise RuntimeError("Must call setup() before prove()")
        if len(transactions) >= self._max_txs:
            raise ValueError(
                f"Need at least 1 free slot: {len(transactions)} txs >= max_txs {self._max_txs}"
            )

        public, private = self._compute_witness_inputs(
            old_state_root, new_state_root, transactions, tx_commitment
        )

        # Try native proving
        if self._zkey_path is not None and self._zkey_path.exists():
            try:
                return self._prove_native(public, private)
            except (OSError, subprocess.SubprocessError, subprocess.TimeoutExpired) as e:
                logger.warning("Native prove failed (%s), falling back to Python", e)

        # Fallback to Python
        if self._pk is None:
            self._pk, self._vk = groth16.setup(self._circuit)
        return groth16.prove(self._pk, private=private, public=public, circuit=self._circuit)

    def verify(
        self,
        proof: Proof,
        old_state_root: bytes,
        new_state_root: bytes,
        tx_commitment: bytes,
    ) -> bool:
        """Verify proof (always uses Python — verification is fast)."""
        if not self._is_setup:
            raise RuntimeError("Must call setup() before verify()")

        old_root_int = _to_field(old_state_root)
        new_root_int = _to_field(new_state_root)
        tx_commit_int = _to_field(tx_commitment)

        public_inputs = [old_root_int, new_root_int, tx_commit_int]
        return groth16.verify(self._vk, proof, public_inputs)

    @property
    def verification_key(self) -> VerificationKey:
        if self._vk is None:
            raise RuntimeError("Must call setup() before accessing verification_key")
        return self._vk

    def _build_circuit(self, max_txs: int) -> Circuit:
        """Build the execution-trace chain circuit (same as Groth16ProofBackend)."""
        c = Circuit()
        old_root = c.public("old_state_root")
        new_root = c.public("new_state_root")
        tx_commit = c.public("tx_commitment")

        tx_signals = [c.private(f"tx_{i}") for i in range(max_txs)]
        chain = old_root * tx_signals[0]
        for i in range(1, max_txs):
            chain = chain * tx_signals[i]
        c.constrain(chain, new_root * tx_commit)
        return c

    def _compute_witness_inputs(
        self,
        old_state_root: bytes,
        new_state_root: bytes,
        transactions: list[L2Tx],
        tx_commitment: bytes,
    ) -> tuple[dict[str, int], dict[str, int]]:
        """Compute public/private inputs (same logic as Groth16ProofBackend.prove)."""
        old_root_int = _to_field(old_state_root)
        new_root_int = _to_field(new_state_root)
        tx_commit_int = _to_field(tx_commitment)

        private: dict[str, int] = {}
        product = old_root_int
        for i, tx in enumerate(transactions):
            tx_int = _to_field(tx.tx_hash())
            private[f"tx_{i}"] = tx_int
            product = _field(product * tx_int)

        target = _field(new_root_int * tx_commit_int)
        if product == 0:
            raise ValueError(
                "Cannot construct proof: accumulated product is zero in the field."
            )
        balance = _field(target * pow(product, FIELD_MODULUS - 2, FIELD_MODULUS))
        private[f"tx_{len(transactions)}"] = balance

        for i in range(len(transactions) + 1, self._max_txs):
            private[f"tx_{i}"] = 1

        public = {
            "old_state_root": old_root_int,
            "new_state_root": new_root_int,
            "tx_commitment": tx_commit_int,
        }
        return public, private

    def _run_setup(self, r1cs_path: Path, zkey_path: Path, vkey_path: Path) -> None:
        """Run snarkjs groth16 setup + export verification key."""
        # Phase 1: Powers of tau (snarkjs powersoftau new bn128 12 pot.ptau)
        pot_path = self._working_dir / "pot.ptau"
        pot_final_path = self._working_dir / "pot_final.ptau"

        subprocess.run(
            [self._setup_binary, "powersoftau", "new", "bn128", "12", str(pot_path)],
            check=True, capture_output=True, timeout=60,
        )
        subprocess.run(
            [self._setup_binary, "powersoftau", "prepare", "phase2", str(pot_path), str(pot_final_path)],
            check=True, capture_output=True, timeout=60,
        )

        # Phase 2: Groth16 setup
        subprocess.run(
            [self._setup_binary, "groth16", "setup", str(r1cs_path), str(pot_final_path), str(zkey_path)],
            check=True, capture_output=True, timeout=120,
        )

        # Export verification key
        subprocess.run(
            [self._setup_binary, "zkey", "export", "verificationkey", str(zkey_path), str(vkey_path)],
            check=True, capture_output=True, timeout=30,
        )

    def _prove_native(self, public: dict[str, int], private: dict[str, int]) -> Proof:
        """Generate proof using native binary."""
        witness_data = export_witness_json(public, private, self._circuit)
        witness_path = self._working_dir / "witness.json"
        witness_path.write_text(json.dumps(witness_data))

        proof_path = self._working_dir / "proof.json"
        public_path = self._working_dir / "public.json"

        # Detect prover type
        if "rapidsnark" in self._prover_binary:
            # rapidsnark <zkey> <witness> <proof> <public>
            subprocess.run(
                [self._prover_binary, str(self._zkey_path), str(witness_path),
                 str(proof_path), str(public_path)],
                check=True, capture_output=True, timeout=self._prove_timeout,
            )
        else:
            # snarkjs groth16 prove <zkey> <witness> <proof> <public>
            subprocess.run(
                [self._prover_binary, "groth16", "prove",
                 str(self._zkey_path), str(witness_path),
                 str(proof_path), str(public_path)],
                check=True, capture_output=True, timeout=self._prove_timeout,
            )

        proof_data = json.loads(proof_path.read_text())
        return parse_snarkjs_proof(proof_data)
